blueprint:
  name: Light - Occupied and Time
  description: >
    Controls a light based on an occupied toggle and time of day
  domain: automation
  input:
    occupied_toggle:
      name: Occupied Toogle
      selector:
        entity:
          domain: input_boolean
    light_switch:
      name: Light Switch
      selector:
        entity:
          domain: light
    time_of_day:
      name: Time of day
      selector:
        select:
          options:
            - Day
            - Evening
            - Night
            - Early Morning

trigger:
  - platform: state
    entity_id: input_select.time_of_day
    id: time
    to: !input time_of_day
  - platform: state
    entity_id:
      - !input occupied_toggle
    to: "on"
    id: motion
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: motion
          - condition: state
            entity_id: input_select.time_of_day
            state: !input time_of_day
      - condition: and
        conditions:
          - condition: trigger
            id: time
          - condition: state
            entity_id: !input occupied_toggle
            state: "on"
action:
  - service: light.turn_on
    target:
      entity_id: !input light_switch
  - wait_for_trigger:
      - platform: state
        entity_id:
          - !input occupied_toggle
        to: "off"
  - service: light.turn_off
    target:
      entity_id: !input light_switch
mode: restart
