blueprint:
  name: Camera Record Movement
  description: >
    Activates camera recording when movement is detected.
  domain: automation
  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    camera:
      name: Camera
      selector:
        entity:
          domain: camera
trigger:
  - platform: state
    entity_id: !input motion_sensor
    to: 'on'
action:
  - service: camera.record
    data:
      duration: 30
      lookback: 0
      filename: /tmp/{{ entity_id.name }}_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4
    target:
      entity_id: !input camera
mode: single
